---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invitcation
  name: invitcation
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invitcation
  strategy: {}
  template:
    metadata:
      labels:
        app: invitcation
    spec:
      containers:
      - image: baluaddagatla/container_app_sample
        name: wedding-app
        ports:
        - containerPort: 3000
