apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  labels:
    app: jmeter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
        - name: jmeter
          image: alpine/jmeter
          args:
            - -n
            - -t
            - /tests/wedding_test.jmx
            - -l
            - /tests/results.jtl
          volumeMounts:
            - name: jmeter-test
              mountPath: /tests
      restartPolicy: Always
      volumes:
        - name: jmeter-test
          configMap:
            name: jmeter-test
