apiVersion: v1
kind: Service
metadata:
  name: weddingapp
  namespace: default
  labels:
    app: weddingapp
spec:
  type: NodePort
  selector:
    app: weddingapp
  ports:
    - name: weddingapp
      port: 5678
      targetPort: 3000
      nodePort: 32767   # valid range: 30000-32767
  sessionAffinity: None
