apiVersion: v1
kind: Service
metadata:
  labels:
    app: weddingapp
  name: weddingapp
  namespace: default
spec:
  ports:
  - name: 5678-3000
    nodePort: 32769
    port: 5678
    protocol: TCP
    targetPort: 3000
  selector:
    app: weddingapp
  sessionAffinity: None
  type: NodePort
