apiVersion: v1
kind: Service
metadata:
  name: invitcation
  namespace: default
  labels:
    app: invitcation
spec:
  type: NodePort
  selector:
    app: invitcation
  ports:
    - name: invitcation
      targetPort: 3000
      nodePort: 32767   # valid range: 30000-32767
  sessionAffinity: None
