apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-17T19:42:08Z"
  labels:
    app: weddingapp
  name: weddingapp
  namespace: default
  uid: dde52f19-d318-4dee-b2de-96b0fcf9566c
spec:
  clusterIP: 10.100.0.0
  clusterIPs:
  - 10.100.0.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5678-3000
    nodePort: 32769
    port: 5678
    protocol: TCP
    targetPort: 3000
  selector:
    app: weddingapp
  sessionAffinity: None
  type: NodePort
